#pragma once

typedef enum Status {
	// String
	// 实例自身状态
	NULLSTRING = -1,
	AVAILABLE = 0,
	NULLBUFFER = 1,
	EMPTYSTRING = 2,
	BLANKSTRING = 3,

	// 操作错误状态
	FAILEDTOCOMBINE = 4,
	WRONGSTRINGSTATUS = 5,
	FAILEDTOREALLOC = 6,
	FAILEDTOALLOC = 7,

	// 转换状态
	NULLINT = 8,
	OVERFLOWINT = 9,
	NOTINT = 10,
	SUCCEEDTOINT = 11,

	NULLLONG = 12,
	OVERFLOWLONG = 13,
	NOTLONG = 14,
	SUCCEEDTOLONG = 15,

	NULLLONGLONG = 16,
	OVERFLOWLONGLONG = 17,
	NOTLONGLONG = 18,
	SUCCEEDTOLONGLONG = 19,

	NULLFLOAT = 20,
	OVERFLOWFLOAT = 21,
	NOTFLOAT = 22,
	SUCCEEDTOFLOAT = 23,

	NULLDOUBLE = 24,
	OVERFLOWDOUBLE = 25,
	NOTDOUBLE = 26,
	SUCCEEDTODOUBLE = 27,

	// 字符数组状态
	NULLCHAR = 28,

	// 检索状态
	IDXOUTBOUNDS = 29,
	SUCCESSFULIDX = 30,
	SUCCEEDTOTRUNCATESTRING = 31,


	// ArrayList
	// ArrayList状态
	NULLAL = -2,
	AVAILABLEAL = 100,
	INVALIDALTYPESIZE = 101,
	WRONGALSTATUS = 102,
	NULLALELEMENT = 103,
	ALLOCALFAIL = 104,
}Status;